language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test --no-fail-on-warnings
  - npm run build --no-fail-on-warnings
  - node ./server/dbtest.js
  - node ./server/ProxySMSTest.js

